# Generated by Django 2.1.7 on 2019-03-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=256)),
                ('currency', models.CharField(blank=True, max_length=256)),
                ('base', models.CharField(blank=True, max_length=256)),
                ('weight', models.CharField(blank=True, max_length=256)),
                ('limit', models.CharField(blank=True, max_length=256)),
                ('host', models.CharField(blank=True, max_length=256)),
                ('key', models.CharField(blank=True, max_length=256)),
                ('api', models.CharField(blank=True, max_length=256)),
                ('action', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.CharField(choices=[('NEW', 'NEW'), ('HANDLED', 'HANDLED'), ('IGNORED', 'IGNORED')], default='NEW', max_length=512)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=512)),
                ('event_occured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
