# Generated by Django 2.1.7 on 2019-03-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190312_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='exchange',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
